nf:
  host: scp1.scp.5gc.mnc099.mcc208.3gppnetwork.org
  nrf_uri: http://nrf.5gc.mnc099.mcc208.3gppnetwork.org
  nssf_uri: http://nssf.5gc.mnc099.mcc208.3gppnetwork.org
  name: scp1.scp.5gc.mnc099.mcc208.3gppnetwork.org
  allowed_nssai: # type Vec<ExtSnssai>
    - sst: 1
      sd: '000001'
    - sst: 1
      sd: '000002'
  nssai: # type Vec<ExtSnssai>
    - sst: 1
      sd: '000001'
    - sst: 1
      sd: '000002'
  plmns:
    - mcc: '001'
      mnc: '01'
  allowed_plmns:
    - mcc: '001'
      mnc: '01'

scp:
  mode: 'D'
  next_hop: false
  next_scp: ''
  dumper_interval: 600
  log_folder: /root/logs